import { test, expect } from '@playwright/test'
import { FRAMES } from '../src/screens.js'

test('all 13 screens render with assets and fit the viewport', async ({ page }, testInfo) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  for (const frame of FRAMES) {
    await page.goto(`/#/${frame.id}`)
    await expect(page.locator('#screen')).toHaveAttribute('data-screen', frame.id)
    await expect(page.locator('#screen > .scr')).toBeVisible()
    await expect.poll(() => page.locator('#orig').evaluate(image => image.complete && image.naturalWidth > 0)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (['signin', 'discover', 'avatar'].includes(frame.id)) {
      await page.screenshot({ path: testInfo.outputPath(`${frame.id}.png`), animations: 'disabled' })
    }
  }
  expect(errors).toEqual([])
})

test('sign in, tabs, likes, history and reload work', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('#screen')).toHaveAttribute('data-screen', 'discover')
  await page.getByRole('button', { name: 'Friends', exact: true }).click()
  await expect(page.locator('#screen')).toHaveAttribute('data-screen', 'friends')
  const like = page.locator('[data-action="like"]').first()
  await like.click()
  await expect(like).toHaveAttribute('aria-pressed', 'true')
  await expect(like).toHaveText('5')
  await page.goBack()
  await expect(page.locator('#screen')).toHaveAttribute('data-screen', 'discover')
  await page.goForward()
  await expect(page.locator('#screen')).toHaveAttribute('data-screen', 'friends')
  await page.reload()
  await expect(page.locator('#screen')).toHaveAttribute('data-screen', 'friends')
  await expect(page.locator('[data-action="like"]').first()).toHaveText('4')
})

test('song drops and comments clear submitted inputs', async ({ page }) => {
  await page.goto('/#/discover')
  await page.getByRole('button', { name: 'Drop a song', exact: true }).click()
  await page.locator('[data-action="pick"]').first().click()
  await page.getByLabel('Your note').fill('A rainy afternoon song')
  await expect(page.locator('#drop-count')).toHaveText('22/500')
  await page.getByRole('button', { name: 'Drop it', exact: true }).click()
  await expect(page.locator('#screen')).toHaveAttribute('data-screen', 'discover')
  await page.locator('[data-go="song"]').first().click()
  await expect(page.locator('.comment').first()).toContainText('A rainy afternoon song')
  const comment = page.getByLabel('What does this song mean to you?')
  await comment.fill('<My favorite chorus>')
  await page.getByRole('button', { name: 'Post comment', exact: true }).click()
  await expect(comment).toHaveValue('')
  await expect(page.locator('.comment').first()).toContainText('<My favorite chorus>')
})

test('friend search, requests and messages work', async ({ page }) => {
  await page.goto('/#/add-friends')
  await page.getByRole('searchbox').fill('@noor')
  await expect(page.locator('#add-list > li')).toHaveCount(1)
  const request = page.locator('[data-action="addFriend"]')
  await request.click()
  await expect(request).toHaveText('Requested')
  await request.click()
  await expect(request).toHaveText('Add')
  await page.goto('/#/conversation')
  await page.getByRole('textbox', { name: 'Message', exact: true }).fill('Listen to this one')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.locator('.bub.me').last()).toHaveText('Listen to this one')
  await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toHaveValue('')
})

test('avatar edits save, cancel and work from a deep link', async ({ page }) => {
  await page.goto('/#/profile')
  const original = await page.locator('.me-card .av').innerHTML()
  await page.getByRole('button', { name: 'Edit avatar', exact: true }).click()
  await page.getByRole('button', { name: 'Next Top', exact: true }).click()
  await expect(page.locator('output').first()).toHaveText('Tee')
  await page.getByRole('button', { name: 'Color 1', exact: true }).click()
  await page.getByRole('button', { name: 'Save avatar', exact: true }).click()
  await expect(page.locator('#screen')).toHaveAttribute('data-screen', 'profile')
  expect(await page.locator('.me-card .av').innerHTML()).not.toBe(original)
  await page.getByRole('button', { name: 'Edit avatar', exact: true }).click()
  await page.getByRole('button', { name: 'Next Top', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.locator('#screen')).toHaveAttribute('data-screen', 'profile')
  await page.getByRole('button', { name: 'Edit avatar', exact: true }).click()
  await expect(page.locator('output').first()).toHaveText('Tee')
  const deepLinkPage = await page.context().newPage()
  await deepLinkPage.goto('/#/avatar')
  await deepLinkPage.getByRole('button', { name: 'Next Top', exact: true }).click()
  await expect(deepLinkPage.locator('output').first()).toHaveText('Tee')
  await deepLinkPage.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(deepLinkPage.locator('#screen')).toHaveAttribute('data-screen', 'profile')
  await deepLinkPage.close()
})

test('song sending and review controls work', async ({ page }) => {
  await page.goto('/?dev#/song')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await page.locator('[data-action="sendPick"][aria-pressed="true"]').first().click()
  await page.locator('[data-action="sendPick"][aria-pressed="true"]').first().click()
  await expect(page.locator('[data-action="send"]')).toBeDisabled()
  await page.locator('[data-action="sendPick"]').first().click()
  await page.getByRole('button', { name: 'Send to 1 friend', exact: true }).click()
  await expect(page.locator('#screen')).toHaveAttribute('data-screen', 'song')
  await page.locator('#pill').click()
  await expect(page.locator('#panel')).toBeVisible()
  await page.getByLabel('Overlay original frame').check()
  await expect(page.locator('#orig')).toBeVisible()
  await page.getByLabel('Show hotspots').check()
  await expect(page.locator('#frame')).toHaveClass('frame hot')
  await page.getByRole('button', { name: 'Restart', exact: true }).click()
  await expect(page.locator('#screen')).toHaveAttribute('data-screen', 'signin')
})